# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" , "development"]

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: check dart version
        run: dart --version

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.7.3

      - name: check flutter version
        run: flutter --version

      - name: call flutter doctor
        run: flutter doctor

      - name: flutter cleaning
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build generated files
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

